INSERT INTO prim_md(csoport, sequence, leiras, ertek) 
VALUES 
('P_NYELV', 1, 'C#', DEFAULT),
('P_NYELV', 2, 'C++', DEFAULT),
('P_NYELV', 3, 'Delphi', DEFAULT),
('P_NYELV', 4, 'Java', DEFAULT),
('P_NYELV', 5, 'JavaScript', DEFAULT),
('P_NYELV', 6, 'Perl', DEFAULT),
('P_NYELV', 7, 'PHP', DEFAULT),
('P_NYELV', 8, 'PHP7', DEFAULT),
('P_NYELV', 9, 'Python', DEFAULT),
('P_NYELV', 10, 'Ruby', DEFAULT),
('P_NYELV', 11, 'Visual Basic', DEFAULT),

('ELFOG_FILE_NEV', 1, 'primC#.csv', '1'),
('ELFOG_FILE_NEV', 2, 'primC++.csv', '2'),
('ELFOG_FILE_NEV', 3, 'primDelphi.csv', '3'),
('ELFOG_FILE_NEV', 4, 'primJava.csv', '4'),
('ELFOG_FILE_NEV', 5, 'primJS.csv', '5'),
('ELFOG_FILE_NEV', 6, 'primPython.csv', '9'),
('ELFOG_FILE_NEV', 7, 'primVB.csv', '11'),

('METODUS', 1, 'Szál nélküli', 'Prim1'),
('METODUS', 2, 'Normál', 'Prim2'),
('METODUS', 3, 'Hatvány', 'Prim3'),
('METODUS', 4, 'Fibonacci', 'Prim4'),
('METODUS', 5, 'Pascal normál', 'Prim50'),
('METODUS', 6, 'Pascal optimális', 'Prim51'),
('METODUS', 7, 'Pascal páratlan', 'Prim52'),
('METODUS', 8, 'Arányos', 'Prim6'),
('METODUS', 9, 'Öszetett', 'Prim70'),
('METODUS', 10, 'Félprím', 'Prim8'),
('METODUS', 11, 'Prím', 'Prim71'),
('METODUS', 12, 'Koch-görbe', 'Prim91'),
('METODUS', 13, 'Inverz négyzetes', 'Prim90'),
('METODUS', 14, 'Egyedi', 'Prim10'),

('TARTOMANY', 1, '1000', DEFAULT),
('TARTOMANY', 2, '10000', DEFAULT),
('TARTOMANY', 3, '100000', DEFAULT),
('TARTOMANY', 4, '1000000', DEFAULT),
('TARTOMANY', 5, '10000000', DEFAULT);